space/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.main, name='main'),
   path('main', views.main, name='main'),
   path('register', views.register, name='register'),
   path('space/<str:id>', views.space, name='space'),
   path('space/book/<str:id>', views.book, name='book'),
   path('host_booking_list', views.host_booking_list, name='host_booking_list'),
   path('booking_list', views.booker_booking_list, name='booker_booking_list'),
   path('search_space', views.search_space, name='search_space'),
   path('search', views.search, name='search'),
   
   # review
   path('create_review/<str:space_id>', views.create_review, name="create_review"),
   path('delete_review/<str:space_id>/<str:review_id>/', views.delete_review, name="delete_review"),
   
   # question
   path('create_question/<str:id>', views.create_question, name="create_question"),
   path('create_question/<str:space_id>/<str:question_id>', views.create_answer, name="create_answer"),
]

withCloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from space import views as space

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', space.firstpage, name='firstpage'),
    path('account/', include('account.urls')),
    path('space/', include('space.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

space/models.py
from django.db import models
from account.models import User
from django.utils import timezone
from django.db.models.deletion import CASCADE
from django.core.validators import RegexValidator
from taggit.managers import TaggableManager
from datetime import datetime

# 1. Space      (fk- User<Host>)
# 2. Review    (fk- Space, User)
# 3. Question  (fk- Space, User)
# 4. Answer     (fk- Question, User<Host>)
# 4. Booking    (fk- Space, User)

class Space(models.Model):
    # space_id
    host_id = models.ForeignKey('account.User', on_delete=models.CASCADE, null=True)
    space_name = models.CharField(max_length=30)
    SPACE_TYPE_CHOICES = [
        ('STUDY', '스터디룸'),
        ('STUDIO', '촬영스튜디오'),
        ('CAFE', '카페 단체석'),
        ('RESTAURANT', '음식점 단체석'),
        ('MEETING', '회의실'),
        ('ETC', '기타')
    ]
    space_type = models.CharField(
        max_length=10,
        choices=SPACE_TYPE_CHOICES,
        default='STUDY'
    )
    contactNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})')
    contact_number = models.CharField(validators = [contactNumberRegex], max_length = 11, unique = True)
    price = models.IntegerField() # 시간당 가격
    space_brief_detail = models.CharField(max_length=200)
    space_detail = models.TextField()
    tags = TaggableManager(blank=True)
    address = models.CharField(max_length=200, default='')
    url = models.URLField()
    space_likes = models.IntegerField(default=0)
    space_image = models.ImageField(upload_to="space/", blank=True, null=True)

    
    def __str__(self):
        return self.space_name


class Booking(models.Model):
    # booking_id
    space_id = models.ForeignKey(Space, on_delete=models.CASCADE, null=True)
    user_id = models.ForeignKey('account.User', on_delete=models.CASCADE, null=True)
    booker_name = models.CharField(max_length = 50, default='')
    phoneNumberRegex = RegexValidator(regex = r'^01([0|1|6|7|8|9])-?([0-9]{3,4})-?([0-9]{4})')
    phoneNumber = models.CharField(validators = [phoneNumberRegex], max_length = 11, unique = True)
    num_of_people = models.IntegerField()
    num_of_vaccinated = models.IntegerField()
    booking_date = models.DateField()
    booking_start = models.TimeField()
    booking_end = models.TimeField()
    
    def __str__(self):
        return self.booker_name
    
    def hour(self):
        h = self.booking_end.hour - self.booking_start.hour
        return h
    
    def time(self):
        h = self.booking_end.hour - self.booking_start.hour
        m = self.booking_end.minute - self.booking_start.minute
        return h*60 + m
    
    def payment(self):
        return int(self.time()/6) * self.space_id.price
    
class Review(models.Model):
    # review_id
    space_id = models.ForeignKey(Space, on_delete=models.CASCADE, null=True)
    user_id = models.ForeignKey('account.User', on_delete=models.CASCADE, null=True)
    review_content = models.TextField()
    RATING_TYPE_CHOICES = [
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5)       
    ]
    review_star = models.CharField(
        max_length = 5,
        choices = RATING_TYPE_CHOICES,
        default = '1'
    )
    
    def __str__(self):
        return self.review_content
    
    def time(self):
        return int((self.booking_end - self.booking_start).seconds / 60)
    
class Question(models.Model):
    # question_id
    space_id = models.ForeignKey(Space, on_delete=models.CASCADE, null=True)
    writer = models.CharField(max_length=50, default='')
    question_content = models.TextField()
    
    def __str__(self):
        return self.question_content


class Answer(models.Model):
    # answer_id
    question_id =models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    user_id = models.ForeignKey('account.User', on_delete=models.CASCADE, null=True) # space의 host_id
    answer_content = models.TextField()
    
    def __str__(self):
        return self.answer_content

space/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.db.models import Q

"""
First Page
"""

def firstpage(request):
    return render(request, 'firstpage.html')

"""
Main Page
"""
def main(request):
    spaces = Space.objects.all()
    return render(request, 'main.html', {'spaces': spaces})


"""
Space Model
"""
# 공간 운영자의 공간 등록 페이지 렌더링
def register_space(request):
    return render(request, 'register_space.html')


# 새로운 공간 등록 페이지 - 데이터 POST
def register(request):
    if request.method == "POST":
        new_space = Space()
        new_space.space_name = request.POST['space_name']
        new_space.space_type = request.POST['space_type']
        new_space.contact_number = request.POST['contact_number']
        new_space.price = request.POST['price']
        new_space.space_brief_detail = request.POST['space_brief_detail']
        new_space.space_detail = request.POST['space_detail']
        new_space.address = request.POST['address']
        new_space.url = request.POST['url']
        new_space.space_image = request.FILES.get('space_image')
        
        host_id = request.user.id
        new_space.host_id = User.objects.get(id=host_id)
        new_space.save()
        
        tags = request.POST.get('tags', '').split(',')
        for tag in tags:
            tag = tag.strip()
            new_space.tags.add(tag)
        return redirect('main')
    else:
        return render(request, 'register.html')


# 공간 검색 페이지
def search_space(request):
    if request.method == 'POST':
        keyword = request.POST.get('search_button') # keyword를 입력받음
        
        # hashtag_q = Q(tags__name__icontains = keyword)
        space_name_q = Q(space_name__icontains = keyword)
        space_type_q = Q(space_type__icontains = keyword)
        address_q = Q(address__icontains = keyword)
        detail_q = Q(space_detail__icontains = keyword)
        brief_detail_q = Q(space_brief_detail__icontains = keyword)
       
        
        space = Space.objects.filter(address_q | space_name_q | space_type_q | detail_q | brief_detail_q )

        return render(request, 'search_result.html', {'space':space, 'keyword':keyword})
    elif request.method == 'GET':
        return redirect('/')

    
# 공간 검색 결과 페이지 (검색 필터링 구현 후 리다이렉팅으로 변경)
def search_result(request):
    return render(request, 'search_result.html')

def search(request):
    return render(request, 'search_space.html')

# 공간 디테일 페이지 (공간 pk=id 값으로 페이지 렌더링)
def space(request, id):
    if request.method == 'POST':
        pk = request.POST.get('pk', None)
        space = get_object_or_404(Space, pk=pk)
    else:
        space = get_object_or_404(Space, pk=id)
        space_id = id
        return render(request, 'space2.html', {'space':space, 'space_id':space_id})


# 예약자의 공간 예약 페이지
def booker_booking(request, id):
    space_id = id
    space = get_object_or_404(Space, pk=space_id)
    return render(request, 'booking_page.html', {'space': space})


"""
Review Model
"""
# 리뷰 생성
def create_review(request, space_id):
    if request.method == 'POST':
        review = Review()
        review.space_id = get_object_or_404(Space, pk=space_id)
        
        user_id = request.user.id
        review.user_id = User.objects.get(id=user_id)
        review.review_content = request.POST['review_content']
        review.review_star = request.POST['review_star']
        review.save()
        return redirect('space', space_id)


# 리뷰 삭제
def delete_review(request, space_id, review_id):
    my_review = Review.objects.get(pk=review_id)
    my_review.delete()
    return redirect('space', space_id)


"""
Question Model
"""
# 질문 생성
def create_question(request, id):
    space_id = id
    if request.method == 'POST':
        question = Question()
        question.space_id = get_object_or_404(Space, pk=space_id)
        question.writer = request.POST['writer']
        question.question_content = request.POST['question_content']
        question.save()
        return redirect('space', space_id)
    

"""
Answer Model
"""
# 질문에 대한 답변 달기
def create_answer(request, space_id, question_id):
    if request.method == 'POST':
        answer = Answer()
        answer.space_id = get_object_or_404(Space, pk=space_id)
        answer.question_id = get_object_or_404(Question, pk=question_id)
        answer.answer_content = request.POST['answer_content']
        answer.save()
        return redirect('space', space_id)


"""
Booking Model
"""
# 새로운 예약 생성
def book(request, id):
    space_id = id
    space = get_object_or_404(Space, pk = space_id)
    if request.method == "POST":
        new_booking = Booking()
        new_booking.space_id = space
        new_booking.booker_name = request.POST['booker_name']
        new_booking.phoneNumber = request.POST['phoneNumber']
        new_booking.num_of_people = request.POST['num_of_people']
        new_booking.num_of_vaccinated = request.POST['num_of_vaccinated']
        new_booking.booking_date = request.POST['booking_date']
        new_booking.booking_start = request.POST.get('booking_start')
        new_booking.booking_end = request.POST.get('booking_end')
        
        user_id = request.user.id
        new_booking.user_id = User.objects.get(id=user_id)
        new_booking.save()
        return redirect('booker_booking_list')
    else:
        return render(request, 'booking_page.html', {'space':space, 'space_id':space_id})
    

# 예약자의 공간 예약 리스트 페이지 (마이페이지 연동)
def booker_booking_list(request):
    book = Booking.objects.all()
    return render(request, 'booker_booking_list.html', {'book':book})


# 공간 운영자의 공간에 대한 예약 리스트 페이지
def host_booking_list(request):
    space = Space.objects.all()
    book = Booking.objects.all()
    return render(request, 'host_booking_list.html', {'book':book, 'space':space})


# 결제 페이지
def payment(request):
    return render(request, 'payment.html')

space/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- bootstrap, jquery 사용을 위한 코드 -->
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!-- <link rel="stylesheet" href="{% static 'css/footer_style.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/main_header.css' %}"> -->
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <header>
        <div class="header1">
            <div class="header1_contents">

                <div id="h1_logo" style="margin-right: 10px;">
                    <a href="{% url 'main' %}">
                        <img src="{% static 'images/WithSpaceLogo.jpg' %}" alt="이미지 로드 안됨" width="100px"> </a>
                </div>
                <div id="h1_logo">
                    <a href="{% url 'main' %}">
                        withSpace
                    </a>
                </div>
                {% if user.is_authenticated %}
                <div id="h_button1"><a href="{% url 'search' %}">공간검색</a></div>
                <span id="h_button2"><a href="{% url 'register' %}">공간등록</a></span>
                {% else %}
                <div id="h_button1"><a href="{% url 'search' %}">공간검색</a></div>
                <span id="h_button2"><a href="{% url 'main' %}">공간 둘러보기</a></span>
                {% endif %}

                <div class="h_col2_bf">
                    <!-- <div class="btn-group"> -->
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                        aria-expanded="false">&nbsp;&nbsp;</button>
                    <ul class="dropdown-menu" role="menu">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'mypage' %}">마이페이지</a></li>
                        <li><a href="{% url 'host_booking_list' %}">등록한 공간</a></li>
                        <li><a href="{% url 'booker_booking_list' %}">예약한 공간</a></li>
                        <li><a href="{% url 'logout' %}">로그아웃</a></li>
                        {% else %}
                        <li><a href="{% url 'signup' %}">회원가입</a></li>
                        <li><a href="{% url 'login' %}">로그인</a></li>
                        {% endif %}

                    </ul>
                    <!-- </div> -->
                    {% if user.is_authenticated %}
                    <div id="name">
                        <p>{{request.user}} 님</p>
                    </div>
                    {% else %}
                    <div id="name">
                        <p> 방문자님 </p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    {% block content %}

    {% endblock %}

    <footer class="footer" style="margin-top: 50px">
        <div class="margin">
            <span style="color: #ffffff;">순천향대학교 & 한국기술교욱대학교 연합해커톤</span><br>
            <span style="color: #ffffff;">이예빈, 배연주, 차주원, 고다혜</span><br>
            <span style="color: #ffffff;">E팀은 2팀</span><br>
            <div>
                <a href="https://github.com/KnS-hacks/2-WithSpace"
                    style="color: #ffffff;">https://github.com/KnS-hacks/2-WithSpace
                </a>
            </div>
            <div text-align="right" style="color: #ffffff;">feat. 멋쟁이 사자처럼</div>
        </div>
    </footer>
</body>

</html>

space/templates/booker_booking_list.html
{% extends 'base.html' %}
{% load static %}
{% block link %} {% static 'css/style.css' %}{% endblock %}
{% block title %} 예약자의 예약 리스트 페이지 {% endblock %}
{% block content %}

<style>
    table {
        width: 1000px;
        border-top: 1px solid #000000;
        border-collapse: collapse;
    }

    th,
    td {
        border-bottom: 1px solid #000000;
        border-left: 1px solid #000000;
        padding: 15px;
    }

    th:first-child,
    td:first-child {
        border-left: none;
    }
</style>
<aside class="container">
    <div style="margin-bottom: 40px; margin-top: 40px;">
        <span style="font-size: 35px; font-weight: bolder;">{{ request.user }} 님의 예약 리스트입니다.</span> <br>
    </div>

    <br>
    <div style="padding: 20px 3px 20px">
        <span style="font-weight: bolder; font-size: 27px;">예약 정보</span><br>
    </div>
    {% for b in book %}
    {% if b.user_id == reqeust.user %}
    <div class="info_table">
        <table>
            <tr>
                <td width="200"><b>예약자 이름</b></td>
                <td>{{ b.booker_name }}</td>
            </tr>
            <td><b>전화번호</b></td>
            <td>{{ b.phoneNumber }}</td>
            </tr>
            <tr>
                <td><b>공간명</b></td>
                <td><a href="{% url 'space' b.space_id.id %}">{{ b.space_id }}</a></td>
            </tr>
            <tr>
                <td><b>예약 총 인원</b></td>
                <td>{{ b.num_of_people }} 명</td>
            </tr>
            <tr>
                <td><b>백신 접종 인원</b></td>
                <td>{{ b.num_of_vaccinated }} 명</td>
            </tr>
            <tr>
                <td><b>예약 날짜</b></td>
                <td>{{b.booking_date}}</td>
            </tr>
            <tr>
                <td><b>예약 시간</b></td>
                <td> {{b.booking_start}} ~ {{b.booking_end}} ({{b.time}}분)</td>
            </tr>
            <tr>
                <td><b>총 결제 금액</b></td>
                <td>{{b.payment}} 원</td>
            </tr>
        </table>
    </div>
    <br><br>
    {% endif %}
    {% endfor %} <br>
</aside>


{% endblock %}

space/templates/booking_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %} booking page {% endblock %}
{% block link %} {% static 'css/style.css' %}{% endblock %}
{% block content %}

<style>
    .input_container {
        padding-bottom: 20px;
    }

    .input_text {
        border-radius: 8px;
        border: 1px solid #9D9D9D;
        height: 30px;
    }

    .input_text:focus {
        outline: none;
    }

    .register_button {
        width: 200px;
        border-radius: 8px;
        border: 1px solid #9D9D9D;
        background-color: #CAD9EC;
        height: 30pt
    }

    .time_class {
        width: 410px;
        display: flex;
        justify-content: space-between;
        align-items: flex-end;
    }
</style>
<form method="post" action="{% url 'book' space.id %}" enctype='multipart/form-data'>
    {% csrf_token %}

    <div class="container" style="margin-left: 37%; min-width: 50px">
        <div style="margin-bottom: 40px; margin-top: 40px;">
            <span style="font-size: 35px; font-weight: bolder;"> <b>{{ space.space_name }} </b>예약하기</span>
        </div>


        <div>
            <div class="input_container">
                <div>
                    <div id=title><b>예약 대표자 이름</b></div>
                    <input class="input_text" type="text" name="booker_name" placeholder="예약 대표자 이름을 입력해주세요."
                        style="width: 410px;">
                </div>
            </div>


            <div class="input_container">
                <div>
                    <div id=title><b>전화 번호</b></div>
                    <input class="input_text" type="text" name="phoneNumber" style="width: 410px;"
                        placeholder="전화 번호를 입력해주세요.">
                </div>
            </div>


            <div class="input_container">
                <div id=title><b>예약 인원</b></div>
                <input class="input_text" type="number" name="num_of_people" style="width: 203px;"
                    placeholder="총 인원 (명)">
                <input class="input_text" type="number" name="num_of_vaccinated" style="width: 203px;"
                    placeholder="백신 접종자 (명)">
            </div>


            <div class="input_container">
                <div>
                    <div id=title><label for="booking_date">예약 날짜 설정 </label></div>
                    <input class="input_text" type="date" name="booking_date" value="2021-11-15" id="start"
                        min="2021-11-15" max="2022-12-31">
                </div>
            </div>

            <div class="input_container time_class">
                <div>
                    <div id="title">
                        <label for="booking_start">예약 시작 시간 </label>
                    </div>
                    <input class="input_text" type="text" id="time1" name="booking_start"
                        style="width:120px; height: 25px;">
                </div>

                <div>
                    <div id="title">
                        <label for="booking_end">예약 종료 시간 </label>
                    </div>
                    <input class="input_text" type="text" id="time2" name="booking_end"
                        style="width:120px; height: 25px;">
                    {{ booking.duration }}
                </div>
                <button type="button" id="sum" style="height:30px;">금액 확인하기</button>
            </div>


            <span><strong>총 결제 금액: </strong></span>
            <input type="text" id="result"
                style="width:100px; border:none; border-right:0px; border-top:0px; boder-left:0px; boder-bottom:0px;"
                dir="rtl">원
            <div style="padding-bottom: 40px;">
                <br>
                <button class="register_button" type="submit">예약 완료</button>
            </div>
        </div>

    </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script type="text/javascript" src="/static/js/time.js"></script>
    <script>
        var price = "{{space.price}}";
        var btns = document.querySelector('#sum');

        btns.addEventListener('click', e => {
            var start_time = document.getElementById('time1').value;
            var start = start_time.split(' ');
            var start_h = start[0].split(':');

            var end_time = document.getElementById('time2').value;
            var end = end_time.split(' ');
            var end_h = end[0].split(':');

            var duration = (end_h[0] - start_h[0]) + ((end_h[1] - start_h[1]) / 60);
            document.getElementById('result').value = price * duration;
        })

    </script>
</form>

{% endblock %}

space/templates/space.html
{% extends 'base.html' %}
{% load static %}
{% include "django/forms/widgets/input.html" %}
{% block title %} 공간에 대한 디테일 페이지 {% endblock %}
{% block link %} {% static 'css/table.css' %}{% endblock %}

{% block content %}
{{ form.media }}

<!-- 공간 상세 페이지 -->

{% if space.space_image %}
사진 : <img src="{{space.space_image.url}}" width="150">
{% endif %}

<div> 공간 운영자 : {{space.host_id}} </div>
<div> 공간 이름 : {{space.space_name}} </div>
<div> 공간 유형 : {{space.space_type}}</div>
<div> 전화번호 : {{space.contact_number}}</div>
<div> 시간당 가격 : {{space.price}}</div>
<div> 공간 정보 : {{space.space_brief_detail}}</div>
<div> 공간 상세 정보: {{space.space_detail}}</div>
<div> 태그 : {% for tag in space.tags.all %}
    #{{ tag.name }}
    {% endfor %}
</div>
<div>주소 : {{ space.address }}
    <div id="map" style="width:500px; height:350px;"></div>
</div>
<div> 사이트 주소 : <a>{{space.url}}</a></div>
<div> 좋아요 수 : {{space.space_likes}}</div>

<br>

<button><a href="{% url 'book' space.id %}"> 예약하기 </a></button>


<hr>

<!-- 리뷰 -->
{% if user.is_authenticated %}
<form action="{% url 'create_review' space.id %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="review_star"> 공간 별점:</label>
        <select name="review_star">
            <option value=1>⭐</option>
            <option value=2>⭐⭐</option>
            <option value=3>⭐⭐⭐</option>
            <option value=4>⭐⭐⭐⭐</option>
            <option value=5>⭐⭐⭐⭐⭐</option>
        </select>
    </div>
    <div>
        <textarea name="review_content" cols="70" rows="10" placeholder="{{space.space_name}}의 시설은 어땠나요?"></textarea>
    </div>
    <input type="submit" value="리뷰 등록">
</form>
{% endif %}

<br>

<!-- 모든 리뷰 보기 -->
<h2> 리뷰 보기 </h2>
<div>
    {% for review in space.review_set.all %}
    <div style="border: 1px solid black; width:300px;">
        <div>
            {{ review.user_id }}

            {% if review.review_star == '1' %}
            <span text-align="left">⭐</span>
            {% elif review.review_star == '2' %}
            <span>⭐⭐</span>
            {% elif review.review_star == '3' %}
            <span>⭐⭐⭐</span>
            {% elif review.review_star == '4' %}
            <span>⭐⭐⭐⭐</span>
            {% elif review.review_star == '5' %}
            <span>⭐⭐⭐⭐⭐</span>
            {% endif %}

        </div>
        {{ review.review_content|linebreaksbr }}
    </div>
    {% endfor %}
</div>

<!-- Q&A -->
<h2> Q&A </h2>
<form action="{% url 'create_question' space.id %}" method="POST">
    {% csrf_token %}
    질문 작성자 : <input type="text" name="writer" placeholder="작성자 이름"> <br>
    질문 내용: <br>
    <textarea name="question_content" cols="70" rows="5" placeholder="{{space.space_name}}에 대해 궁금한 점이 있나요?"></textarea>
    <button type="submit"> 리뷰 등록 </button>
</form>
<br>


<!-- 모든 질문 보기 -->
<h2> Questions </h2>
{% for question in space.question_set.all %}
<b>{{ question.writer|linebreaksbr }} </b>님의 질문 : {{ question.question_content|linebreaksbr }} <br>

<!-- 현재 user가 공간 등록자와 동일한 유저라면 위의 질문에 대한 답변 등록 가능-->
{% if request.user == space.host_id %}
<h4> 공간 운영자 {{user}} 님의 답변 달기 </h4>
<form action="{% url 'create_answer' space.id question.id %}" method="POST">
    {% csrf_token %}
    답변 :
    <textarea name="question_content" cols="30" rows="5"
        placeholder="{{question.writer}}님의 질문에 대한 답을 달아주세요."></textarea>
    <button type="submit"> 답변 등록 </button>
</form>
{% endif %}
{% endfor %}

<script type="text/javascript"
    src="//dapi.kakao.com/v2/maps/sdk.js?appkey=ee557e514b7deb78145a876b3049a7e1&libraries=services"></script>
<script>
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };

    // 지도를 생성합니다
    var map = new kakao.maps.Map(mapContainer, mapOption);

    // 주소-좌표 변환 객체를 생성합니다
    var geocoder = new kakao.maps.services.Geocoder();
    var address = "{{space.address}}";
    var mark = "{{space.space_name}}";

    window.addEventListener('load', e => {
        geocoder.addressSearch(address, function (result, status) {

            // 정상적으로 검색이 완료됐으면 
            if (status === kakao.maps.services.Status.OK) {

                var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                // 결과값으로 받은 위치를 마커로 표시합니다
                var marker = new kakao.maps.Marker({
                    map: map,
                    position: coords
                });

                // 인포윈도우로 장소에 대한 설명을 표시합니다
                var infowindow = new kakao.maps.InfoWindow({
                    content: '<div style="width:150px;text-align:center;padding:6px 0;">' + mark + '</div>'
                });
                infowindow.open(map, marker);

                // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                map.setCenter(coords);
            }
        });

    })
</script>

{% endblock %}